import gql from 'graphql-tag';

export const ingredientApiSchema = gql`
  extend type Query {
    "List Ingredients"
    ingredients(options: IngredientListOptions): IngredientList!

    "Get an Ingredient either by id or slug. If neither 'id' nor 'slug' is specified, an error will result."
    ingredient(id: ID, slug: String): Ingredient
  }

  extend type Mutation {
    "Create new Ingredient"
    createIngredient(input: CreateIngredientInput!): Ingredient

    "Update existing Ingredient"
    updateIngredient(input: UpdateIngredientInput!): Ingredient
  }

  # Todo: generated by generateListOptions function
  input IngredientListOptions {
    skip: Int
    take: Int
  }

  input CreateIngredientInput {
    name: String!
    calories: Float!
    totalFat: Float!
    saturatedFat: Float!
    transFat: Float!
    cholesterol: Float!
    sodium: Float!
    totalCarbs: Float!
    fiber: Float!
    totalSugars: Float!
    addedSugars: Float!
    protein: Float!
    vitaminD: Float!
    potassium: Float!
    calcium: Float!
    iron: Float!
  }

  input UpdateIngredientInput {
    id: ID!
    name: String!
  }
`;
